name: CI
on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [Windows, Ubuntu, MacOS]

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: nox -s tests
